env: 
  action: destroy

name: rds_deployer
on:
  workflow_run:
    workflows: ["vpc_deployer"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     AWS_DEFAULT_REGION: us-east-1
     AWS_DEFAULT_OUTPUT: json

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Initialize
        working-directory: rds
        run: |
          terraform init

          
      - name: Validate
        working-directory: rds
        run: |
          terraform validate

      - name: Apply
        working-directory: rds
        run: |
          terraform ${{env.action}} -auto-approve

          

